# Generated by Django 3.0.7 on 2021-02-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210218_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='no_of_doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, verbose_name='door'),
        ),
    ]
